EnableDefaultLinters: true
linters:
  ParserErrors:
    enabled: false
  SpaceInHtmlTag:
    enabled: false
  ErbSafety:
    enabled: true
  ClosingErbTagIndent:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Layout/FirstArgumentIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Layout/CommentIndentation:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
